name: freetheleashkids
favicon: null
layout_spectrum: 0.09106404380872846
typography_spectrum: 0.9165160483680665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aecff0'
    - '#7ab0ec'
    - '#3a8ba9'
    - '#3c4e76'
    - '#000525'
  brandStrength: 0.5
  lightness: 0.07485963054932654
  saturation: 0.993834079708904
  rhythmicContrast: 0.09721300401724875
purpose: []
