name: freetheleashkids
favicon: null
layout_spectrum: 0.09106404380872846
typography_spectrum: 0.9165160483680665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.30126155517064035
  lightness: 0.07485963054932654
  saturation: 0.993834079708904
  rhythmicContrast: 0.09721300401724875
purpose: []
